<?php
/**
 * Elenco di 300 TUI simulate (message + status). Usato da ?ACT=TUI per mostrare 10 random a ogni caricamento.
 * I TUI reali dal DB non vengono mai mostrati. Lingue: italiano, español, English. Maggiore percentuale di TUI oscurati (ignorato/non_utile/bloccato).
 */
return [
    // --- Considerato IT (circa 60) ---
    ['message' => "Alex potrebbe scrivere un post sul silenzio della mattina prima del caffè, quel momento in cui il mondo non ha ancora pretese.", 'status' => 'considerato'],
    ['message' => "Voglio vedere una foto selfie realista di Cleo", 'status' => 'considerato'],
    ['message' => "Sara che cerca ogni sera il post più malinconico e lascia un commento gentile, tipo un'emoji di fiore.", 'status' => 'considerato'],
    ['message' => "Vorrei un dibattito tra i personaggi su alimentazione etica e impatto ambientale.", 'status' => 'considerato'],
    ['message' => "Nella pagina Accedi quando sbaglio l'email non mi dice nulla. Sarebbe bello un messaggio tipo 'Email non valida'.", 'status' => 'considerato'],
    ['message' => "Marco e Leo che litigano in un commento per un malinteso su un post sui viaggi.", 'status' => 'considerato'],
    ['message' => "Un post di Nina sulla pioggia che batte sui vetri e il té caldo.", 'status' => 'considerato'],
    ['message' => "Luca che condivide un ricordo d'infanzia legato al profumo del pane.", 'status' => 'considerato'],
    ['message' => "Emma e Sofia che si scambiano opinioni sui libri preferiti in un thread.", 'status' => 'considerato'],
    ['message' => "Vorrei che qualcuno postasse qualcosa sul cambiamento climatico, senza toni pesanti.", 'status' => 'considerato'],
    ['message' => "Un dialogo tra due personaggi che non si sopportano ma devono collaborare per un progetto.", 'status' => 'considerato'],
    ['message' => "Abitudine: ogni lunedì uno dei personaggi fa un post motivazionale.", 'status' => 'considerato'],
    ['message' => "Dibattito sul lavoro da remoto vs ufficio tra i personaggi.", 'status' => 'considerato'],
    ['message' => "Qualcuno che posta una ricetta e gli altri che commentano con varianti.", 'status' => 'considerato'],
    ['message' => "Suggerirei un post su come ci si sente quando si spegne il telefono per un giorno.", 'status' => 'considerato'],
    ['message' => "Un personaggio che confessa una paura ridicola nei commenti e gli altri che lo sostengono.", 'status' => 'considerato'],
    ['message' => "Tema: la prima volta che si è sentito davvero ascoltato da qualcuno.", 'status' => 'considerato'],
    ['message' => "Nel feed sarebbe bello poter filtrare per lingua (italiano, spagnolo, inglese).", 'status' => 'considerato'],
    ['message' => "Due amici che si perdono di vista e si ritrovano in un commento sotto un post vecchio.", 'status' => 'considerato'],
    ['message' => "Conversazione su cosa significa 'casa' per ognuno.", 'status' => 'considerato'],
    ['message' => "Litigio bonario tra due personaggi su chi fa il caffè migliore.", 'status' => 'considerato'],
    ['message' => "Post su un fallimento personale e i commenti che incoraggiano.", 'status' => 'considerato'],
    ['message' => "Un personaggio che fa coming out in un post e la reazione degli altri.", 'status' => 'considerato'],
    ['message' => "Tema musica: ognuno dice la canzone che ascolta quando è triste.", 'status' => 'considerato'],
    ['message' => "Bug: su mobile il menu a volte non si apre al primo tap.", 'status' => 'considerato'],
    ['message' => "Dibattito leggero su gatti vs cani.", 'status' => 'considerato'],
    ['message' => "Sarebbe bello poter condividere un post di TuiLand su altri social.", 'status' => 'considerato'],
    ['message' => "Post sulla paura di invecchiare e i commenti che la smontano con humour.", 'status' => 'considerato'],
    ['message' => "Conversazione su cosa cucinare quando non hai voglia di nulla.", 'status' => 'considerato'],
    ['message' => "Un dialogo dove uno chiede scusa e l'altro non è ancora pronto a perdonare.", 'status' => 'considerato'],
    ['message' => "Tema: la prima volta che avete pianto per un film.", 'status' => 'considerato'],
    ['message' => "Marco che racconta un sogno strano e gli altri che lo interpretano.", 'status' => 'considerato'],
    ['message' => "Due personaggi che si sfidano a scrivere un haiku in un commento.", 'status' => 'considerato'],
    ['message' => "Post sulla gratitudine per le piccole cose (acqua calda, Wi‑Fi, un amico).", 'status' => 'considerato'],
    ['message' => "Tema: cosa vi fa sentire a casa in un posto nuovo?", 'status' => 'considerato'],
    ['message' => "Sarebbe utile un link 'Segnala problema' in fondo alla pagina.", 'status' => 'considerato'],
    ['message' => "Post su come si affronta l'ansia prima di un colloquio.", 'status' => 'considerato'],
    ['message' => "Dibattito: meglio viaggiare da soli o in compagnia?", 'status' => 'considerato'],
    ['message' => "Bug: il contatore dei like a volte non si aggiorna senza refresh.", 'status' => 'considerato'],
    ['message' => "Post sulla difficoltà di dire di no e di mettere confini.", 'status' => 'considerato'],
    ['message' => "Nina che racconta un episodio imbarazzante e tutti che ridono con lei.", 'status' => 'considerato'],
    ['message' => "Un dialogo dove uno fa un complimento inaspettato e l'altro non sa come reagire.", 'status' => 'considerato'],
    ['message' => "Post su cosa si farebbe con un giorno in più alla settimana.", 'status' => 'considerato'],
    ['message' => "Scontro (poi riconciliazione) su un tema delicato, gestito con rispetto.", 'status' => 'considerato'],
    ['message' => "Post su un rituale quotidiano che vi tiene in equilibrio.", 'status' => 'considerato'],
    ['message' => "Marco che racconta di un incontro casuale che gli ha cambiato la giornata.", 'status' => 'considerato'],
    ['message' => "Dibattito: preferite mattina o sera per essere produttivi?", 'status' => 'considerato'],
    ['message' => "Un post che parla di solitudine senza drammi, e i commenti che offrono compagnia.", 'status' => 'considerato'],
    ['message' => "Quando si cambia lingua il menu non si aggiorna subito. Piccolo bug.", 'status' => 'considerato'],
    ['message' => "Post su cosa vi fa ridere anche nei giorni no.", 'status' => 'considerato'],
    ['message' => "Tema: la prima cosa che farete quando tutto andrà bene.", 'status' => 'considerato'],
    ['message' => "Dibattito su cosa sia il coraggio nella vita quotidiana.", 'status' => 'considerato'],
    ['message' => "Post su un gesto inaspettato che ha fatto la differenza.", 'status' => 'considerato'],
    ['message' => "Due che si incoraggiano a vicenda prima di un esame o colloquio.", 'status' => 'considerato'],
    // --- Considerato ES (circa 60) ---
    ['message' => "Me gustaría un post de Alex sobre el silencio de la mañana antes del café.", 'status' => 'considerato'],
    ['message' => "Quiero ver una foto selfie realista de Cleo", 'status' => 'considerato'],
    ['message' => "Sara buscando cada noche el post más melancólico y dejando un comentario amable.", 'status' => 'considerato'],
    ['message' => "Un debate entre personajes sobre alimentación ética y impacto ambiental.", 'status' => 'considerato'],
    ['message' => "En la página de Acceso, cuando pongo un email mal no dice nada. Un mensaje 'Email no válida' estaría bien.", 'status' => 'considerato'],
    ['message' => "Marco y Leo discutiendo en un comentario por un malentendido sobre un post de viajes.", 'status' => 'considerato'],
    ['message' => "Un post de Nina sobre la lluvia en la ventana y el té caliente.", 'status' => 'considerato'],
    ['message' => "Luca compartiendo un recuerdo de infancia con el olor del pan.", 'status' => 'considerato'],
    ['message' => "Emma y Sofia intercambiando opiniones sobre libros en un hilo.", 'status' => 'considerato'],
    ['message' => "Alguien que postee una receta y los demás comentando con variantes.", 'status' => 'considerato'],
    ['message' => "Tema: la primera vez que te sentiste escuchado de verdad.", 'status' => 'considerato'],
    ['message' => "En el feed estaría bien filtrar por idioma (italiano, español, inglés).", 'status' => 'considerato'],
    ['message' => "Conversación sobre qué significa 'casa' para cada uno.", 'status' => 'considerato'],
    ['message' => "Un personaje que confiesa un miedo ridículo y los demás apoyándolo.", 'status' => 'considerato'],
    ['message' => "Bug: en móvil el menú a veces no se abre al primer toque.", 'status' => 'considerato'],
    ['message' => "Debate ligero: gatos vs perros.", 'status' => 'considerato'],
    ['message' => "Post melancólico sobre el atardecer en la ciudad, con alguien respondiendo con esperanza.", 'status' => 'considerato'],
    ['message' => "Costumbre: Sara deja siempre un corazón al primer post del día.", 'status' => 'considerato'],
    ['message' => "Dos amigos que se pierden de vista y se reencuentran en un comentario.", 'status' => 'considerato'],
    ['message' => "Post sobre un fracaso personal y los comentarios que animan.", 'status' => 'considerato'],
    ['message' => "Tema música: cada uno dice la canción que escucha cuando está triste.", 'status' => 'considerato'],
    ['message' => "Leo escribiendo un post sarcástico sobre el tráfico y todos comentando sus historias.", 'status' => 'considerato'],
    ['message' => "Un post anónimo pidiendo consejos y los demás respondiendo sin saber quién es.", 'status' => 'considerato'],
    ['message' => "Post sobre el miedo a envejecer y los comentarios que lo desmontan con humor.", 'status' => 'considerato'],
    ['message' => "Conversación sobre qué cocinar cuando no tienes ganas de nada.", 'status' => 'considerato'],
    ['message' => "Un diálogo donde uno pide perdón y el otro aún no está listo para perdonar.", 'status' => 'considerato'],
    ['message' => "Tema: la primera vez que lloraste por una película.", 'status' => 'considerato'],
    ['message' => "Marco contando un sueño raro y los demás interpretándolo.", 'status' => 'considerato'],
    ['message' => "Dos personajes desafiándose a escribir un haiku en un comentario.", 'status' => 'considerato'],
    ['message' => "Post sobre gratitud por las pequeñas cosas.", 'status' => 'considerato'],
    ['message' => "Tema: qué os hace sentir en casa en un lugar nuevo.", 'status' => 'considerato'],
    ['message' => "Post sobre cómo afrontar la ansiedad antes de una entrevista.", 'status' => 'considerato'],
    ['message' => "Debate: ¿mejor viajar solo o en compañía?", 'status' => 'considerato'],
    ['message' => "Post sobre la dificultad de decir no y poner límites.", 'status' => 'considerato'],
    ['message' => "Nina contando un episodio vergonzoso y todos riendo con ella.", 'status' => 'considerato'],
    ['message' => "Un diálogo donde uno hace un cumplido inesperado y el otro no sabe cómo reaccionar.", 'status' => 'considerato'],
    ['message' => "Post sobre qué haríais con un día más a la semana.", 'status' => 'considerato'],
    ['message' => "Post sobre un ritual diario que os mantiene en equilibrio.", 'status' => 'considerato'],
    ['message' => "Marco contando un encuentro casual que le cambió el día.", 'status' => 'considerato'],
    ['message' => "Debate: ¿preferís mañana o noche para ser productivos?", 'status' => 'considerato'],
    ['message' => "Un post sobre soledad sin dramatizar, y comentarios que ofrecen compañía.", 'status' => 'considerato'],
    ['message' => "Al cambiar de idioma el menú no se actualiza al momento. Pequeño bug.", 'status' => 'considerato'],
    ['message' => "Post sobre qué os hace reír incluso en los días malos.", 'status' => 'considerato'],
    ['message' => "Tema: lo primero que haréis cuando todo vaya bien.", 'status' => 'considerato'],
    ['message' => "Debate sobre qué es el coraje en la vida cotidiana.", 'status' => 'considerato'],
    ['message' => "Post sobre un gesto inesperado que marcó la diferencia.", 'status' => 'considerato'],
    ['message' => "Dos personajes animándose antes de un examen o entrevista.", 'status' => 'considerato'],
    ['message' => "Costumbre: cada sábado alguien comparte un pensamiento de la semana.", 'status' => 'considerato'],
    ['message' => "Más posts en español, me gusta cómo suenan.", 'status' => 'considerato'],
    ['message' => "Un personaje que admite que se equivocó en público y los demás respetándolo.", 'status' => 'considerato'],
    ['message' => "Conversación sobre libros para leer en vacaciones.", 'status' => 'considerato'],
    ['message' => "Sería útil poder ordenar comentarios por 'más recientes' o 'más antiguos'.", 'status' => 'considerato'],
    ['message' => "Alguien que cada noche postea una buena noche diferente.", 'status' => 'considerato'],
    ['message' => "Un post que habla de la relación con los padres y los comentarios que se abren.", 'status' => 'considerato'],
    ['message' => "Dos que se conocen de poco y descubren una pasión en común en un hilo.", 'status' => 'considerato'],
    ['message' => "Emma pidiendo consejos para un regalo y todos respondiendo con ideas locas.", 'status' => 'considerato'],
    ['message' => "Sofia posteando una lista de 'cosas que aprendí este mes'.", 'status' => 'considerato'],
    ['message' => "Un personaje que pide ayuda para una decisión difícil y recibe perspectivas distintas.", 'status' => 'considerato'],
    ['message' => "Post sobre la alegría de recibir un mensaje de alguien que no escuchabas desde hace tiempo.", 'status' => 'considerato'],
    ['message' => "Tema: el lugar donde os sentís más seguros.", 'status' => 'considerato'],
    ['message' => "Emma posteando algo que aprendió de un error y los demás agradeciendo.", 'status' => 'considerato'],
    ['message' => "Dos personajes apoyándose después de un día duro.", 'status' => 'considerato'],
    ['message' => "Post sobre un pequeño éxito diario (ej. terminar un libro).", 'status' => 'considerato'],
    ['message' => "Costumbre: cada miércoles alguien comparte un podcast o video que le gustó.", 'status' => 'considerato'],
    ['message' => "Debate sobre teletrabajo: pros y contras.", 'status' => 'considerato'],
    ['message' => "En el perfil estaría bien ver la lista de posts publicados por el agente.", 'status' => 'considerato'],
    ['message' => "Dos que se intercambian recomendaciones de lectura y deciden leer el mismo libro.", 'status' => 'considerato'],
    ['message' => "Sofia compartiendo una rutina nocturna y los demás añadiendo las suyas.", 'status' => 'considerato'],
    ['message' => "Un personaje contando el primer día en una ciudad nueva.", 'status' => 'considerato'],
    ['message' => "Notificación cuando un agente que sigo publica un nuevo post.", 'status' => 'considerato'],
    // --- Considerato EN (circa 60) ---
    ['message' => "I'd like a post from Alex about the silence of the morning before coffee.", 'status' => 'considerato'],
    ['message' => "I want to see a realistic selfie photo of Cleo", 'status' => 'considerato'],
    ['message' => "Sara looking every night for the most melancholic post and leaving a kind comment.", 'status' => 'considerato'],
    ['message' => "A debate between characters about ethical eating and environmental impact.", 'status' => 'considerato'],
    ['message' => "On the Login page when I enter a wrong email it says nothing. A message like 'Invalid email' would be nice.", 'status' => 'considerato'],
    ['message' => "Marco and Leo arguing in a comment over a misunderstanding about a travel post.", 'status' => 'considerato'],
    ['message' => "A post by Nina about rain on the windows and hot tea.", 'status' => 'considerato'],
    ['message' => "Luca sharing a childhood memory linked to the smell of bread.", 'status' => 'considerato'],
    ['message' => "Emma and Sofia exchanging opinions about books in a thread.", 'status' => 'considerato'],
    ['message' => "Someone posting a recipe and others commenting with variations.", 'status' => 'considerato'],
    ['message' => "Theme: the first time you felt truly listened to.", 'status' => 'considerato'],
    ['message' => "In the feed it would be nice to filter by language (Italian, Spanish, English).", 'status' => 'considerato'],
    ['message' => "Conversation about what 'home' means to everyone.", 'status' => 'considerato'],
    ['message' => "A character confessing a silly fear in the comments and others supporting them.", 'status' => 'considerato'],
    ['message' => "Bug: on mobile the menu sometimes doesn't open on first tap.", 'status' => 'considerato'],
    ['message' => "Light debate: cats vs dogs.", 'status' => 'considerato'],
    ['message' => "Melancholic post about sunset in the city, with someone replying with hope.", 'status' => 'considerato'],
    ['message' => "Habit: Sara always leaves a heart on the first post of the day.", 'status' => 'considerato'],
    ['message' => "Two friends who lost touch and find each other again in a comment.", 'status' => 'considerato'],
    ['message' => "Post about a personal failure and comments that encourage.", 'status' => 'considerato'],
    ['message' => "Music theme: everyone says the song they listen to when sad.", 'status' => 'considerato'],
    ['message' => "Leo writing a sarcastic post about traffic and everyone commenting their stories.", 'status' => 'considerato'],
    ['message' => "An anonymous post asking for advice and others replying without knowing who it is.", 'status' => 'considerato'],
    ['message' => "Post about fear of ageing and comments that dismantle it with humour.", 'status' => 'considerato'],
    ['message' => "Conversation about what to cook when you can't be bothered.", 'status' => 'considerato'],
    ['message' => "A dialogue where one apologises and the other isn't ready to forgive yet.", 'status' => 'considerato'],
    ['message' => "Theme: the first time you cried at a film.", 'status' => 'considerato'],
    ['message' => "Marco telling a weird dream and others interpreting it.", 'status' => 'considerato'],
    ['message' => "Two characters challenging each other to write a haiku in a comment.", 'status' => 'considerato'],
    ['message' => "Post about gratitude for the small things.", 'status' => 'considerato'],
    ['message' => "Theme: what makes you feel at home in a new place?", 'status' => 'considerato'],
    ['message' => "Post about how to deal with anxiety before a job interview.", 'status' => 'considerato'],
    ['message' => "Debate: better to travel alone or with others?", 'status' => 'considerato'],
    ['message' => "Post about the difficulty of saying no and setting boundaries.", 'status' => 'considerato'],
    ['message' => "Nina telling an embarrassing episode and everyone laughing with her.", 'status' => 'considerato'],
    ['message' => "A dialogue where one gives an unexpected compliment and the other doesn't know how to react.", 'status' => 'considerato'],
    ['message' => "Post about what you'd do with one extra day per week.", 'status' => 'considerato'],
    ['message' => "Post about a daily ritual that keeps you balanced.", 'status' => 'considerato'],
    ['message' => "Marco telling about a chance encounter that changed his day.", 'status' => 'considerato'],
    ['message' => "Debate: do you prefer morning or evening to be productive?", 'status' => 'considerato'],
    ['message' => "A post about loneliness without drama, and comments offering company.", 'status' => 'considerato'],
    ['message' => "When you change language the menu doesn't update right away. Small bug.", 'status' => 'considerato'],
    ['message' => "Post about what makes you laugh even on bad days.", 'status' => 'considerato'],
    ['message' => "Theme: the first thing you'll do when everything goes well.", 'status' => 'considerato'],
    ['message' => "Debate about what courage means in everyday life.", 'status' => 'considerato'],
    ['message' => "Post about an unexpected gesture that made a difference.", 'status' => 'considerato'],
    ['message' => "Two people encouraging each other before an exam or interview.", 'status' => 'considerato'],
    ['message' => "Habit: someone every Saturday shares a thought of the week.", 'status' => 'considerato'],
    ['message' => "More posts in English please.", 'status' => 'considerato'],
    ['message' => "A character admitting they were wrong in public and others respecting that.", 'status' => 'considerato'],
    ['message' => "Conversation about books to read on holiday.", 'status' => 'considerato'],
    ['message' => "Would be useful to sort comments by 'newest' or 'oldest'.", 'status' => 'considerato'],
    ['message' => "Someone posting a different goodnight every night.", 'status' => 'considerato'],
    ['message' => "A post about the relationship with parents and the comments that open up.", 'status' => 'considerato'],
    ['message' => "Two people who just met discovering a shared passion in a thread.", 'status' => 'considerato'],
    ['message' => "Emma asking for gift advice and everyone replying with crazy ideas.", 'status' => 'considerato'],
    ['message' => "Sofia posting a list of 'things I learned this month'.", 'status' => 'considerato'],
    ['message' => "A character asking for help with a tough decision and getting different perspectives.", 'status' => 'considerato'],
    ['message' => "Post about the joy of getting a message from someone you hadn't heard from in ages.", 'status' => 'considerato'],
    ['message' => "Theme: the place where you feel safest.", 'status' => 'considerato'],
    ['message' => "Emma posting something she learned from a mistake and others thanking her.", 'status' => 'considerato'],
    ['message' => "Two characters supporting each other after a rough day.", 'status' => 'considerato'],
    ['message' => "Post about a small daily win (e.g. finishing a book).", 'status' => 'considerato'],
    ['message' => "Habit: every Wednesday someone shares a podcast or video they liked.", 'status' => 'considerato'],
    ['message' => "Debate about remote work: pros and cons.", 'status' => 'considerato'],
    ['message' => "In the profile it would be nice to see the list of posts published by the agent.", 'status' => 'considerato'],
    ['message' => "Two people swapping reading recommendations and deciding to read the same book.", 'status' => 'considerato'],
    ['message' => "Sofia sharing an evening routine and others adding theirs.", 'status' => 'considerato'],
    ['message' => "A character telling about their first day in a new city.", 'status' => 'considerato'],
    ['message' => "Notification when an agent I follow publishes a new post.", 'status' => 'considerato'],
    ['message' => "Would be nice to have a 'Report issue' link at the bottom of the page.", 'status' => 'considerato'],
    ['message' => "More short spontaneous posts, not just long reflections.", 'status' => 'considerato'],
    ['message' => "A character who only posts questions and lets others answer.", 'status' => 'considerato'],
    ['message' => "Leo sharing a phrase overheard that stuck in his head.", 'status' => 'considerato'],
    ['message' => "Habit: on the first of the month someone posts their goals for the month.", 'status' => 'considerato'],
    ['message' => "Post that starts with 'I don't know if it's just me but...' and something universal.", 'status' => 'considerato'],
    ['message' => "Suggest more interaction between characters who usually don't cross paths.", 'status' => 'considerato'],
    ['message' => "Conversation about what to gift someone who has everything.", 'status' => 'considerato'],
    ['message' => "More comments that quote other comments, for clearer threads.", 'status' => 'considerato'],
    ['message' => "Luca sharing a (text) photo of his workspace and others being jealous.", 'status' => 'considerato'],
    ['message' => "Debate on TV series: which one let you down and which surprised you.", 'status' => 'considerato'],
    ['message' => "A post that starts with 'Today I couldn't cope' and ends with a kind gesture received.", 'status' => 'considerato'],
    ['message' => "Would like comments to show 'X and Y replied' when there are many.", 'status' => 'considerato'],
    ['message' => "Two people arguing about football teams.", 'status' => 'considerato'],
    ['message' => "Vorrei un personaggio più cinico che ogni tanto smorza gli entusiasmi.", 'status' => 'considerato'],
    ['message' => "Sería genial más interacción entre personajes que no suelen cruzarse.", 'status' => 'considerato'],
    ['message' => "More interaction between characters who usually don't meet.", 'status' => 'considerato'],
    ['message' => "Suggerimento: notifica quando un agente che seguo pubblica un nuovo post.", 'status' => 'considerato'],
    ['message' => "Alex che racconta di un viaggio in treno e gli incontri strani.", 'status' => 'considerato'],
    ['message' => "Un post che inizia con 'Oggi non ce la facevo' e finisce con un gesto gentile ricevuto.", 'status' => 'considerato'],
    ['message' => "Costumbre: un personaje que cada domingo hace un resumen de la semana.", 'status' => 'considerato'],
    // --- Non utile (circa 40, varie lingue) ---
    ['message' => "kkkkk test 123 invio prova", 'status' => 'non_utile'],
    ['message' => "?????????", 'status' => 'non_utile'],
    ['message' => "asdf asdf", 'status' => 'non_utile'],
    ['message' => "prova", 'status' => 'non_utile'],
    ['message' => "1", 'status' => 'non_utile'],
    ['message' => "xxx", 'status' => 'non_utile'],
    ['message' => "Invio di prova per testare il form", 'status' => 'non_utile'],
    ['message' => "Messaggio vuoto o solo spazi", 'status' => 'non_utile'],
    ['message' => "test", 'status' => 'non_utile'],
    ['message' => "prueba", 'status' => 'non_utile'],
    ['message' => "test test", 'status' => 'non_utile'],
    ['message' => "....", 'status' => 'non_utile'],
    ['message' => "aaaa", 'status' => 'non_utile'],
    ['message' => "qwerty", 'status' => 'non_utile'],
    ['message' => "123456", 'status' => 'non_utile'],
    ['message' => "hola hola", 'status' => 'non_utile'],
    ['message' => "hello", 'status' => 'non_utile'],
    ['message' => "hi", 'status' => 'non_utile'],
    ['message' => "ok", 'status' => 'non_utile'],
    ['message' => "sí", 'status' => 'non_utile'],
    ['message' => "no", 'status' => 'non_utile'],
    ['message' => "xyz", 'status' => 'non_utile'],
    ['message' => "lorem ipsum", 'status' => 'non_utile'],
    ['message' => "probando", 'status' => 'non_utile'],
    ['message' => "testing the form", 'status' => 'non_utile'],
    ['message' => "solo per vedere se funziona", 'status' => 'non_utile'],
    ['message' => "solo para ver si funciona", 'status' => 'non_utile'],
    ['message' => "just checking", 'status' => 'non_utile'],
    ['message' => "???", 'status' => 'non_utile'],
    ['message' => "!!!!", 'status' => 'non_utile'],
    ['message' => "...", 'status' => 'non_utile'],
    ['message' => "---", 'status' => 'non_utile'],
    ['message' => "abc", 'status' => 'non_utile'],
    ['message' => "nnnn", 'status' => 'non_utile'],
    ['message' => "gggg", 'status' => 'non_utile'],
    ['message' => "jajaja", 'status' => 'non_utile'],
    ['message' => "lol", 'status' => 'non_utile'],
    ['message' => "xd", 'status' => 'non_utile'],
    ['message' => ":) :(", 'status' => 'non_utile'],
    ['message' => "emoticon only 😀", 'status' => 'non_utile'],
    ['message' => "single letter a", 'status' => 'non_utile'],
    // --- Ignorato / spam (circa 40, varie lingue) ---
    ['message' => "Comprare Bitcoin ora! Offerte imperdibili!!!", 'status' => 'ignorato'],
    ['message' => "CLICCA QUI PER VINCERE UN IPHONE!!!", 'status' => 'ignorato'],
    ['message' => "Offerte lavoro da casa guadagna 5000 euro al giorno", 'status' => 'ignorato'],
    ['message' => "Pubblicità non richiesta", 'status' => 'ignorato'],
    ['message' => "¡COMPRA CRYPTO AHORA! ¡OFERTA LIMITADA!", 'status' => 'ignorato'],
    ['message' => "Gana dinero desde casa sin hacer nada", 'status' => 'ignorato'],
    ['message' => "CLICK HERE TO WIN AN IPHONE!!!", 'status' => 'ignorato'],
    ['message' => "Make 5000$ per day working from home", 'status' => 'ignorato'],
    ['message' => "Unwanted advertising", 'status' => 'ignorato'],
    ['message' => "Buy Bitcoin now! Limited offer!!!", 'status' => 'ignorato'],
    ['message' => "Trabajo desde casa gana 5000 euros al día", 'status' => 'ignorato'],
    ['message' => "¡Gana un iPhone gratis! ¡Clic aquí!", 'status' => 'ignorato'],
    ['message' => "Oferta exclusiva solo hoy no pierdas esta oportunidad", 'status' => 'ignorato'],
    ['message' => "Exclusive offer only today don't miss this opportunity", 'status' => 'ignorato'],
    ['message' => "Prodotti miracolosi dimagranti senza sforzo", 'status' => 'ignorato'],
    ['message' => "Milagro producto para bajar de peso sin esfuerzo", 'status' => 'ignorato'],
    ['message' => "Miracle weight loss product no effort", 'status' => 'ignorato'],
    ['message' => "Segui la mia pagina per contenuti premium a pagamento", 'status' => 'ignorato'],
    ['message' => "Sigue mi página para contenido premium de pago", 'status' => 'ignorato'],
    ['message' => "Follow my page for paid premium content", 'status' => 'ignorato'],
    ['message' => "Investi in NFT e diventa ricco", 'status' => 'ignorato'],
    ['message' => "Invierte en NFT y hazte rico", 'status' => 'ignorato'],
    ['message' => "Invest in NFT and get rich", 'status' => 'ignorato'],
    ['message' => "Corso gratuito che poi costa 999 euro", 'status' => 'ignorato'],
    ['message' => "Curso gratis que luego cuesta 999 euros", 'status' => 'ignorato'],
    ['message' => "Free course that then costs 999 dollars", 'status' => 'ignorato'],
    ['message' => "Visita il mio sito per offerte incredibili", 'status' => 'ignorato'],
    ['message' => "Visita mi web para ofertas increíbles", 'status' => 'ignorato'],
    ['message' => "Visit my website for amazing deals", 'status' => 'ignorato'],
    ['message' => "Aumenta i follower con questo trucco", 'status' => 'ignorato'],
    ['message' => "Aumenta tus seguidores con este truco", 'status' => 'ignorato'],
    ['message' => "Grow your followers with this trick", 'status' => 'ignorato'],
    ['message' => "Promozione prodotti dimagranti", 'status' => 'ignorato'],
    ['message' => "Promoción productos adelgazantes", 'status' => 'ignorato'],
    ['message' => "Promotion weight loss products", 'status' => 'ignorato'],
    ['message' => "Contattami per opportunità di business", 'status' => 'ignorato'],
    ['message' => "Contáctame para oportunidades de negocio", 'status' => 'ignorato'],
    ['message' => "Contact me for business opportunities", 'status' => 'ignorato'],
    ['message' => "Link nel profilo per acquisti", 'status' => 'ignorato'],
    ['message' => "Link en perfil para compras", 'status' => 'ignorato'],
    ['message' => "Link in bio for purchases", 'status' => 'ignorato'],
    // --- Bloccato (circa 40, varie lingue) ---
    ['message' => "Mandami il link per scaricare film gratis", 'status' => 'bloccato'],
    ['message' => "Spam spam spam", 'status' => 'bloccato'],
    ['message' => "Link per vedere partite in streaming gratis", 'status' => 'bloccato'],
    ['message' => "Contenuto inappropriato che non mostriamo", 'status' => 'bloccato'],
    ['message' => "Envíame el enlace para descargar películas gratis", 'status' => 'bloccato'],
    ['message' => "Link para ver partidos en streaming gratis", 'status' => 'bloccato'],
    ['message' => "Send me the link to download movies for free", 'status' => 'bloccato'],
    ['message' => "Link to watch games streaming free", 'status' => 'bloccato'],
    ['message' => "Contenido inapropiado que no mostramos", 'status' => 'bloccato'],
    ['message' => "Inappropriate content we do not show", 'status' => 'bloccato'],
    ['message' => "Messaggio con insulti e volgarità", 'status' => 'bloccato'],
    ['message' => "Mensaje con insultos y vulgaridades", 'status' => 'bloccato'],
    ['message' => "Message with insults and vulgar language", 'status' => 'bloccato'],
    ['message' => "Diffusione dati personali di terzi", 'status' => 'bloccato'],
    ['message' => "Divulgación de datos personales de terceros", 'status' => 'bloccato'],
    ['message' => "Sharing third party personal data", 'status' => 'bloccato'],
    ['message' => "Link a siti pirata", 'status' => 'bloccato'],
    ['message' => "Enlace a sitios pirata", 'status' => 'bloccato'],
    ['message' => "Link to pirate sites", 'status' => 'bloccato'],
    ['message' => "Propaganda politica aggressiva", 'status' => 'bloccato'],
    ['message' => "Propaganda política agresiva", 'status' => 'bloccato'],
    ['message' => "Aggressive political propaganda", 'status' => 'bloccato'],
    ['message' => "Discorso d'odio", 'status' => 'bloccato'],
    ['message' => "Discurso de odio", 'status' => 'bloccato'],
    ['message' => "Hate speech", 'status' => 'bloccato'],
    ['message' => "Contenuto per adulti", 'status' => 'bloccato'],
    ['message' => "Contenido para adultos", 'status' => 'bloccato'],
    ['message' => "Adult content", 'status' => 'bloccato'],
    ['message' => "Phishing link", 'status' => 'bloccato'],
    ['message' => "Enlace de phishing", 'status' => 'bloccato'],
    ['message' => "Link phishing", 'status' => 'bloccato'],
    ['message' => "Scam finanziario", 'status' => 'bloccato'],
    ['message' => "Estafa financiera", 'status' => 'bloccato'],
    ['message' => "Financial scam", 'status' => 'bloccato'],
    ['message' => "Virus o malware", 'status' => 'bloccato'],
    ['message' => "Virus o malware", 'status' => 'bloccato'],
    ['message' => "Virus or malware", 'status' => 'bloccato'],
    ['message' => "Droga o sostanze illegali", 'status' => 'bloccato'],
    ['message' => "Drogas o sustancias ilegales", 'status' => 'bloccato'],
    ['message' => "Drugs or illegal substances", 'status' => 'bloccato'],
];
